import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Full-Stack Assesment",
  description: "Generated by create next app, developed by Renz Vitug",
};

export default function RootLayout({ children }: 
  Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <div className="min-h-screen flex flex-col">
          
          <header className="sticky top-0 z-50 w-full border-b bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/60">
            <div className="container mx-auto max-w-10xl px-4 sm:px-6">
              <div className="flex h-20 items-center justify-between">
                
                <div className="flex items-center gap-2">
                  <span className="text-3xl font-bold">NextBlog</span>
                </div>

              </div>
            </div>
          </header>

          <main className="flex-1">{children}</main>

          <footer className="border-t bg-white">
            <div className="container mx-auto max-w-4xl px-4 py-8 sm:px-6">
              <div className="flex flex-col items-center justify-center gap-4 text-center">
                <p className="text-sm text-gray-600">
                  Built by <span className="font-medium text-gray-900">Renz Vitug</span>. 
                </p>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}